theme: minima
title: James' Programming Blog
author: James R Swift
description: Discussions of software stuff, (because I want to try blogging out)

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
